spring.application.name=fintrack2


server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fintrack
spring.datasource.username=root
spring.datasource.password=Polux@244


spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

logging.level.root=info